language: r
warnings_are_errors: true

jobs:
  include:
    - name: "Linux Xenial R-Release"
      os: linux
      dist: xenial
      r: release
      before_install:
        - sudo apt-get install libmpfr-dev
      script:
        - R CMD build .
        - travis_wait 45 R CMD check cliR*tar.gz --as-cran
    - name: "Linux Xenial R-Devel"
      os: linux
      dist: xenial
      r: devel
      before_install:
        - sudo apt-get install libmpfr-dev
      script:
        - R CMD build .
        - travis_wait 45 R CMD check cliR*tar.gz --as-cran
