language: r
warnings_are_errors: true

jobs:
  include:
    - name: "Linux Xenial R-Release"
      os: linux
      dist: xenial
      r: release
    - name: "Linux Xenial R-Devel"
      os: linux
      dist: xenial
      r: devel
    - name: "Mac OSX 9.4 R-Release"
      os: osx
      osx_image: xcode9.4
      r: release
before_install:
  - sudo apt-get install libmpfr-dev
