language: r
warnings_are_errors: true

jobs:
  include:
    - name: "Mac OSX 9.4 R-Release"
      os: osx
      osx_image: xcode9.4
      r: release
      r_github_packages:
        - tidymodels/broom
        - RcppCore/RcppArmadillo
      script:
        - R CMD build .
        - travis_wait 45 R CMD check cliR*tar.gz --as-cran
