language: r
r:
  - release
  - devel
before_install:
  - sudo apt-get install libmpfr-dev
warnings_are_errors: true
os:
  - linux
  - osx
osx_image: xcode9.4
dist: xenial
addons:
  apt:
    packages:
      - libmpfr-dev
