language: r
warnings_are_errors: true

jobs:
  include:
    - name: "Linux Xenial R-Release"
      os: linux
      dist: xenial
      r: release
      r_binary_packages:
        - shiny
        - tidyr
        - RcppEigen
        - minqa
        - RcppArmadillo
      before_install:
        - sudo apt-get install libmpfr-dev
      script:
        - R CMD build .
        - travis_wait 45 R CMD check cliR*tar.gz --as-cran
    - name: "Linux Xenial R-Devel"
      os: linux
      dist: xenial
      r: devel
      r_binary_packages:
        - shiny
        - tidyr
        - RcppEigen
        - minqa
        - RcppArmadillo
      before_install:
        - sudo apt-get install libmpfr-dev
      script:
        - R CMD build .
        - travis_wait 45 R CMD check cliR*tar.gz --as-cran
    - name: "Mac OSX 9.4 R-Release"
      os: osx
      osx_image: xcode9.4
      r: release
      r_github_packages:
        - tidymodels/broom
        - RcppCore/RcppArmadillo
        - r-lib/vctrs
      script:
        - R CMD build .
        - travis_wait 45 R CMD check cliR*tar.gz --as-cran
