language: r
warnings_are_errors: true

jobs:
  include:
    - name: "Linux Xenial R-Release"
      os: linux
      dist: xenial
      r: release
      before_install:
        - sudo apt-get install libmpfr-dev
    - name: "Linux Xenial R-Devel"
      os: linux
      dist: xenial
      r: devel
      before_install:
        - sudo apt-get install libmpfr-dev
    - name: "Mac OSX 9.4 R-Release"
      os: osx
      osx_image: xcode9.4
      r: release
      r_github_packages: tidymodels/broom, RcppCore/RcppArmadillo, r-lib/vctrs
